# This compose file supports running a faucet node that connects to the `validator-testnet`
# compose's json-rpc endpoint. This should be started after that compose has been started.
# The faucet can be accessed at 127.0.0.1:8000
#

# Run client with:
# docker-compose -f docker-compose-client.yaml run client

# SERVICE ADDRESSES:
# Validator
#     rpc:      172.16.1.2:8080,  127.0.0.1:8080
# Fullnode:
#     rpc:      172.16.1.4:8081,  127.0.0.1:8081
# Faucet:       172.16.1.3:8000,  127.0.0.1:8000

version: "3.8"
services:

  # The validator node. This runs inside the validator network (named "vfn")
  validator:
    image: libra/validator:devnet
    cpus: 0.5
    cpuset: "0"
    networks:
      shared:
        ipv4_address: 172.16.1.2
    volumes:
      - type: bind
        source: ./keys/
        target: /opt/diem/keys/
        read_only: true
      - type: bind
        source: ./validator_node.yaml
        target: /opt/diem/etc/validator_node.yaml
        read_only: true
    command: >
      /bin/bash -c "
           mkdir -p /opt/diem/etc/;
           cp /opt/diem/keys/* /opt/diem/etc/;
          /opt/diem/bin/diem-node --config /opt/diem/etc/validator_node.yaml
        "
    ports:
      - "8080:8080"


  # This is a validator fullnode: responsible for forwarding transactions to the validator,
  #                               and receiving blockchain updates from the validator
  fullnode:
    image: libra/validator:devnet
    depends_on:
      - validator
    networks:
      shared:
        ipv4_address: 172.16.1.4
    volumes:
      - type: bind
        source: ./keys/
        target: /opt/diem/keys/
        read_only: true
      - type: bind
        source: ./public_full_node.yaml
        target: /opt/diem/etc/public_full_node.yaml
        read_only: true
    command: >
      /bin/bash -c "
          sleep 3;
          mkdir -p /opt/diem/etc/;
          cp /opt/diem/keys/* /opt/diem/etc/;
          /opt/diem/bin/diem-node --config /opt/diem/etc/public_full_node.yaml
        "
    ports:
      - "8081:8081"

  # The faucet is a special feature for testing, through which you can create new currency
  faucet:
    image: libra/faucet:devnet
    depends_on:
      - validator
      - fullnode
    environment:
      AC_HOST: "172.16.1.4"
      AC_PORT: "8081"
      CFG_CHAIN_ID: "TESTING"
    networks:
      shared:
        ipv4_address: 172.16.1.3
    volumes:
      - type: bind
        source: ./keys/mint.key
        target: /opt/diem/etc/mint.key
        read_only: true
    command: >
      /bin/bash -c "
          sleep 3;
          /opt/diem/bin/diem-faucet \
          --address 0.0.0.0 \
          --port 8000 \
          --chain-id TESTING \
          --mint-key-file-path /opt/diem/etc/mint.key \
          --server-url http://172.16.1.4:8081
        "
    ports:
      - "8000:8000"


networks:
  shared:
    name: "diem-docker-compose-shared"
    ipam:
      config:
        - subnet: 172.16.1.0/24
