# This compose file supports running a faucet node that connects to the `validator-testnet`
# compose's json-rpc endpoint. This should be started after that compose has been started.
# The faucet can be accessed at 127.0.0.1:8000
#
# Place the following files into the same directory:
# * mint.key (also known as the diem_root_key)
# * waypoint.txt
#
# Additional notes:
# * Images can be found at https://hub.docker.com/r/diem/faucet/tags, obtain the latest tag and
# update below.
version: "3.8"
services:
    validator:
        # Note this image currently does not support this, will update to the appropriate minimum
        # version shortly
        image: libra/validator:master_609c0b05
        networks:
            shared:
                ipv4_address: 172.16.1.3
        volumes:
            - type: bind
              source: ./validator_data
              target: /opt/diem/var
        command: [ "/opt/diem/bin/diem-node", "--test", "--config", "/opt/diem/var" ]
        ports:
            - "8081:8080"

    faucet:
        image: libra/faucet:master_609c0b05
        depends_on:
            - validator
        environment:
            AC_HOST: "172.16.1.3"
            AC_PORT: "8081"
            CFG_CHAIN_ID: "TESTING"
        networks:
            shared:
                ipv4_address: 172.16.1.2
        volumes:
            - type: bind
              source: ./validator_data/diem_root_key
              target: /opt/diem/etc/diem_root_key
              read_only: true
        command: >
          /bin/bash -c "
              sleep 1;
              /opt/diem/bin/diem-faucet \
              --address 0.0.0.0 \
              --port 8000 \
              --mint-key-file-path /opt/diem/etc/mint.key \
              --server-url \"${AC_HOST:-172.16.1.3}\"
            "
        ports:
            - "8000:8000"

    fullnode:
        image: libra/validator:master_609c0b05
        depends_on:
            - validator
            - faucet
        volumes:
            - type: volume
              source: db
              target: /opt/diem/data
            - type: bind
              source: ./validator_data/0/genesis.blob
              target: /opt/diem/etc/genesis.blob
              read_only: true
            - type: bind
              source: ./validator_data/waypoint.txt
              target: /opt/diem/etc/waypoint.txt
              read_only: true
            - type: bind
              source: ./public_full_node.yaml
              target: /opt/diem/etc/node.yaml
              read_only: true
        command: >
          /bin/bash -c "
              sleep 1;
              /opt/diem/bin/diem-node -f /opt/diem/etc/node.yaml
            "
        ports:
            - "8080:8080"

volumes:
    db:

networks:
    shared:
        external: true
        name: "diem-docker-compose-shared"
