---
base:
  # This is the location Diem will store its database.
  # It is backed by a dedicated docker volume for persistence.
  data_dir: /opt/diem/var
  role: validator
  # This is a checkpoint into the blockchain for added security.
  waypoint:
    from_storage:
      type: on_disk_storage
      path: /opt/diem/etc/private_keys.json

consensus:
  contiguous_rounds: 2
  max_block_size: 1000
  max_pruned_blocks_in_mem: 100
  round_initial_timeout_ms: 1000
  proposer_type:
    type: leader_reputation
    active_weights: 99
    inactive_weights: 1
  safety_rules:
    backend:
      type: on_disk_storage
      path: /opt/diem/etc/private_keys.json
    logger:
      chan_size: 10000
      is_async: true
      level: INFO
    service:
      type: thread
    test: ~
    verify_vote_proposal_signature: true
    export_consensus_key: false
    network_timeout_ms: 30000
    enable_cached_safety_data: true
  sync_only: false
  mempool_poll_count: 1

execution:
  sign_vote_proposal: true
  genesis_file_location: /opt/diem/etc/genesis.blob
  service:
    type: thread
  backend:
    type: on_disk_storage
    path: /opt/diem/etc/private_keys.json
  network_timeout_ms: 30000

validator_network:
  max_connection_delay_ms: 60000
  connection_backoff_base: 2
  connectivity_check_interval_ms: 5000
  network_channel_size: 1024
  max_concurrent_network_reqs: 100
  discovery_method: onchain
  identity:
    type: from_storage
    backend:
      type: on_disk_storage
      path: /opt/diem/etc/shared_config.json
      namespace: testing
    key_name: validator_network
    peer_id_name: owner_account
  listen_address: /ip4/0.0.0.0/tcp/6180
  mutual_authentication: true
  network_address_key_backend:
    type: on_disk_storage
    path: /opt/diem/etc/private_keys.json
  network_id: validator
  seeds: { }
  max_frame_size: 8388608
  enable_proxy_protocol: false
  ping_interval_ms: 1000
  ping_timeout_ms: 10000
  ping_failures_tolerated: 5
  max_outbound_connections: 3
  max_inbound_connections: 100

debug_interface:
  admission_control_node_debug_port: 6191
  address: 0.0.0.0
  diem_trace:
    sampling:
      block: 1/1
      txn: 1/100
  metrics_server_port: 9101
  public_metrics_server_port: 9102

full_node_networks:
  - max_connection_delay_ms: 60000
    connection_backoff_base: 2
    connectivity_check_interval_ms: 5000
    network_channel_size: 1024
    max_concurrent_network_reqs: 100
    discovery_method: none
    identity:
      type: from_storage
      backend:
        type: on_disk_storage
        path: /opt/diem/etc/private_keys.json
      key_name: fullnode_network
      peer_id_name: owner_account
    listen_address: /ip4/0.0.0.0/tcp/7180
    mutual_authentication: false
    network_address_key_backend: ~
    network_id:
      private: vfn
    seed_addrs: { }
    seeds: { }
    max_frame_size: 8388608
    enable_proxy_protocol: false
    ping_interval_ms: 1000
    ping_timeout_ms: 10000
    ping_failures_tolerated: 5
    max_outbound_connections: 3
    max_inbound_connections: 100
    inbound_rate_limit_config: ~
    outbound_rate_limit_config: ~

state_sync:
  chunk_limit: 1000
  long_poll_timeout_ms: 10000
  max_chunk_limit: 1000
  max_timeout_ms: 120000
  multicast_timeout_ms: 30000
  sync_request_timeout_ms: 60000
  tick_interval_ms: 100

json_rpc:
  # This specifies your JSON-RPC endpoint. Intentionally on public so that Docker can export it.
  address: "0.0.0.0:8080"
  batch_size_limit: 20
  page_size_limit: 1000
  content_length_limit: 32768

upstream:
  networks: [ ]

metrics:
  collection_interval_ms: 1000
  dir: metrics
  enabled: false

logger:
  chan_size: 10000
  is_async: true
  level: WARN

storage:
  address: "127.0.0.1:6666"
  backup_service_address: "127.0.0.1:6186"
  dir: db
  grpc_max_receive_len: 100000000
  prune_window: 1000000
  timeout_ms: 30000
  rocksdb_config:
    max_open_files: 10000
    max_total_wal_size: 1073741824

mempool:
  capacity: 1000000
  capacity_per_user: 100
  default_failovers: 3
  max_broadcasts_per_peer: 1
  mempool_snapshot_interval_secs: 180
  shared_mempool_ack_timeout_ms: 2000
  shared_mempool_backoff_interval_ms: 30000
  shared_mempool_batch_size: 100
  shared_mempool_max_concurrent_inbound_syncs: 2
  shared_mempool_tick_interval_ms: 50
  system_transaction_timeout_secs: 600
  system_transaction_gc_interval_ms: 60000
