---
on:
  push:
    branches: [auto, canary]
    #paths: ['**.md']
  pull_request:
    branches: [main, release-*, gha-test-*]
    #paths: ['**.md']


name: Check markdown links

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
          # On `push` this value will be empty and will "do-the-right-thing"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 #get all the history!!!
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          base-branch: 'main'
          use-verbose-mode: 'yes'
          folder-path: 'developers.diem.com/docs/'
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          base-branch: 'main'
          folder-path: 'developers.diem.com/blog/'
